# Generated by Django 2.0 on 2018-05-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userquery',
            name='probable_faq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='chatbot.FaqQuestion'),
            preserve_default=False,
        ),
    ]
